### ISSUE TITLE
sonoff-server node is missing from the Node-RED palette

### ISSUE THREAD

**Issue by meingraham** [saryn/node-red-contrib-sonoff-server#6]
@saryn 

I have a small issue with the Node-RED sonoff contribution (not sure if I have the terminology right). I am refering to this - https://github.com/saryn/node-red-contrib-sonoff-server

In Node-RED, only four of the five nodes appear in the nodelist. The sonoff-server node is missing. If I go to Manage Palette and filter on 'sonoff', five nodes are displayed. All five show as "enabled" (i.e., the function button displays 'Disable' for all of the nodes). However, the checkbox for the sonoff-server is not "checked" (checkbox is "hollow"). The checkbox for the other four nodes are "selected" and thus those nodes appear in the node palette. I tried toggling the sonoff-server to disabled and then enabled but it had no effect.

I installed your package via npm per your documentation. Is there any other configuration I need to perform to the Node-RED environment? Obviously without being able to run config-server, the server won't run, the Sonoff device will not complete it configuration, and I won't be able to add it to Node-RED.

Thanks.

Mike

P.S. I have succeeded in pairing with a Sonoff device and sending it the access point and server information successfully. It drops its AP and I see it on my WLAN. But then it sits there trying to find the server. I wasn't able to successfully get sonoff.setupdevice.js working. The whole NetworkManager thing got my Raspberry all confused. This is a problem for another day. First thing I need is for the simple-sonoff-server to start up success fully so that when the Sonoff finishes pairing it will find it's server and complete its configuration.

**Comment by mdopp** [comment]
sonoff.setupdevice.js => either use a notebook/pc with linux + network manager, or use a window maschine. I haven't been able to make it run on a raspberry pi yet.

**Comment by betyar** [comment]
I have the exact same problem as above, that is, the sonoff-server node is missing from the palette yet in the configuration files and in node-red it exists but is not enabled and there appears to be no way to enable it. Also when I use netstat to check for ports that are being listened to, the sonoff server doesn't exist while node-red does. 

Does all this mean I need to install simple-sonoff-server separately and then run node-red with the node-red-contrib-sonoff-server module? Or should I run from the command line the config-server script from the config-server directory within the node-red-contrib-sonoff-server module  so as to setup and configure the server? I haven't tried to register a sonoff device yet because it's obvious that the server isn't running and that any attempt to do so will fail, as with the previous comment. I would think that at least I should be able to see the server listening on a port before trying to register any devices.

Any suggestions are much appreciated.

Thanks in advance,
John

**Comment by betyar** [comment]
After trying several different ways to get the server started, I came across this warning message when I launched node-red:

[warn] [node-red-contrib-sonoff-server/sonoff-server] SyntaxError: Unexpected token ...

Any clue of what the problem is exactly?

**Comment by betyar** [comment]
Getting a little closer.

According to this post (https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwiB19fiktrbAhXHKCwKHRVtDBIQFggmMAA&url=https%3A%2F%2Fgithub.com%2Fmdopp%2Fsimple-sonoff-server%2Fissues%2F11&usg=AOvVaw1AzB2ZAbmMcZqvEM-480NH) the problem can be with the node version, that is, if it is less than 4.0 such an error occurs. However, in my case the node version is 4.8.7 and if I run simple-sonoff-server directly the server works (but on node-red it still doesn't show).  I am using the latest version of node-red (0.18.5) so I don't think the problem could be there, or maybe it is?
